### ISSUE TITLE
Problem with dependencies list.

### ISSUE THREAD

**Issue by salamanderrake** [jdart1/arasan-chess#1]
There is none, I needed 3 or 4 libs(I am counting the two tablebase libs/apps) but I did not know I needed them until I tried to build them, also what is Rockstar and where can I get it? Also have you thought about using cmake for configuring the build?

**Comment by jdart1** [comment]
The current dev sources should build just by typing "make", although by default without tablebase support. Build instructions are in the the INSTALL file.

Rockstar and other external libraries (except for tablebases) are no longer used.
