### ISSUE TITLE
Missing Rockstar.hpp(?)

### ISSUE THREAD

**Issue by salamanderrake** [jdart1/arasan-chess#2]
I get this when compiling.

```
rockstar.cpp:3:10: fatal error: 'Rockstar.hpp' file not found
#include "Rockstar.hpp"
         ^
1 error generated.
```

Seems I am missing some rockstar library.
This is on OpenSuse 13.2

**Comment by jdart1** [comment]
closing this because Rockstar is no longer required for compilation.
