### ISSUE TITLE
Go Infinite stops search?

### ISSUE THREAD

**Issue by asdfjkl** [jdart1/arasan-chess#21]
I am testing my GUI against various engines and I stumbled on the following behaviour: After a certain sequence of commands, arasan stops searching and returns bestmove, even though the command was go infinite. Tested: arasan 21.0/x64, arasan 20.5/x32 on Win8.1 x64.

I suspect that the previous "stop" command I am sending before is somehow cached, and then incorrectly processed _after_ go infinite was issued...

Can you reproduce this behaviour?

C:\Users\user\Downloads\arasan21.0>arasanx-64.exe
Arasan 21.0 Copyright 1994-2018 by Jon Dart. All Rights Reserved.
uci
id name Arasan 21.0
id author Jon Dart
option name Hash type spin default 64 min 4 max 64000
option name Ponder type check default true
option name Contempt type spin default 0 min -200 max 200
option name Use tablebases type check default true
option name SyzygyTbPath type string default syzygy
option name SyzygyUse50MoveRule type check default true
option name SyzygyProbeDepth type spin default 4 min 0 max 64
option name MultiPV type spin default 1 min 1 max 10
option name OwnBook type check default true
option name Favor frequent book moves type spin default 50 min 0 max 100
option name Favor best book moves type spin default 50 min 0 max 100
option name Threads type spin default 1 min 1 max 64
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 2600 min 1000 max 2600
uciok
stop
go infinite
failed to open book.bin
info multipv 1 depth 1 score cp 65 time 0 nodes 0 hashfull 0 pv d2d3
info multipv 1 depth 1 score cp 68 time 0 nodes 0 hashfull 0 pv d2d4
info multipv 1 depth 1 score cp 81 time 0 nodes 0 hashfull 0 pv e2e3
info multipv 1 depth 1 score cp 81 time 0 nodes 21 hashfull 0 pv e2e3
bestmove e2e3

same with 20.5
C:\Users\user\Downloads\arasan20.5>arasanx-32.exe
Arasan 20.5 Copyright 1994-2018 by Jon Dart. All Rights Reserved.
uci
id name Arasan 20.5
id author Jon Dart
option name Hash type spin default 64 min 4 max 2000
option name Ponder type check default true
option name Contempt type spin default 0 min -200 max 200
option name Use tablebases type check default true
option name SyzygyTbPath type string default syzygy
option name SyzygyUse50MoveRule type check default true
option name SyzygyProbeDepth type spin default 4 min 0 max 64
option name MultiPV type spin default 1 min 1 max 10
option name OwnBook type check default true
option name Book selectivity type spin default 50 min 0 max 100
option name Threads type spin default 1 min 1 max 64
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 2600 min 1000 max 2600
uciok
stop
go infinite
info multipv 1 depth 1 score cp 64 time 0 nodes 0 hashfull 0 pv d2d3
info multipv 1 depth 1 score cp 67 time 4 nodes 0 hashfull 0 pv d2d4
info multipv 1 depth 1 score cp 80 time 8 nodes 0 hashfull 0 pv e2e3
info multipv 1 depth 1 score cp 80 time 11 nodes 21 hashfull 0 pv e2e3
bestmove e2e3

**Comment by jdart1** [comment]
It isn't usual to issue a "stop" command before "go" when there is no previous search. I don't think UCI GUIs do that. Nevertheless, I have fixed this.

**Comment by asdfjkl** [comment]
Thanks!
