### ISSUE TITLE
missing initialisations in file scoring.cpp, function Scoring::initBitboards()?

### ISSUE THREAD

**Issue by HansLoehle** [jdart1/arasan-chess#22]
I'm not sure, but either there is `backwardW[i].set(sq2);` missing in line 128½ or the assignment to sq2 in line 128 is superflous.
Similar suspected issue for line 158 and a probably missing `backwardB[i].set(sq2);` in line 158½.

**Comment by jdart1** [comment]
I have cleaned up that section of code and removed unnecessary initializations. I don't think anything was functionally wrong with it, though.
