### ISSUE TITLE
Repeat message "failed to open ./book.bin"

### ISSUE THREAD

**Issue by nguyenpham** [jdart1/arasan-chess#25]
I copied Arasan chess alone (without any other files) to a folder for a tournament. It repeats messaging `failed to open ./book.bin` whenever receiving "isready"

**Comment by jdart1** [comment]
The message is harmless: it is just a warning. But further instances of it probably should be suppressed if the "OwnBook" option is set "false."

**Comment by jdart1** [comment]
I am not going to fix this. If you disable the book by setting OwnBook false, the multiple messages should go away.
