### ISSUE TITLE
Compile error on Linux

### ISSUE THREAD

**Issue by rontant** [jdart1/arasan-chess#28]
I got some errors when trying to compile Arasan 22 on my Rock64 Linux box, a RaspberryPi-like SBC.

Please see below:

> root@rock64:~/arasan-chess/src# make -j4
> mkdir -p ../build
> cc -Ofast -flto -fno-rtti -fno-enforce-eh-specs  -DNDEBUG  -std=c++11 -Wall -Wextra -fno-strict-aliasing -DUSE_INTRINSICS -DUSE_ASM -I. -DSYZYGY_TBS -DARASAN_VERSION=v22.0.0-68-g5a00e47 -D_64BIT -DSMP -DSMP_STATS -pthread  -c -o ../build/syzygy.o syzygy.cpp
> mkdir -p ../tune_build
> cc -x c++ -std=c++11 -Wall -Wextra -fno-strict-aliasing -DUSE_INTRINSICS -DUSE_ASM -I. -DSYZYGY_TBS -DARASAN_VERSION=v22.0.0-68-g5a00e47 -D_64BIT -Ofast -flto -fno-rtti -fno-enforce-eh-specs  -DNDEBUG  -c syzygy/src/tbprobe.c -o ../build/tbprobe.o
> mkdir -p ../bin
> mkdir -p ../profile
> mkdir -p ../prof_data
> cd ../build && cc  -fuse-ld=gold -flto  ../build/arasanx.o  ../build/tester.o  ../build/bench.o  ../build/protocol.o  ../build/globals.o  ../build/board.o  ../build/boardio.o  ../build/material.o  ../build/chess.o  ../build/attacks.o  ../build/bitboard.o  ../build/chessio.o  ../build/epdrec.o  ../build/bhash.o  ../build/params.o  ../build/scoring.o  ../build/see.o  ../build/movearr.o  ../build/notation.o  ../build/options.o  ../build/bitprobe.o  ../build/bookread.o  ../build/bookwrit.o  ../build/log.o  ../build/search.o  ../build/searchc.o  ../build/learn.o  ../build/movegen.o  ../build/hash.o  ../build/calctime.o  ../build/eco.o  ../build/ecodata.o  ../build/legal.o  ../build/stats.o  ../build/threadp.o  ../build/threadc.o  ../build/syzygy.o ../build/tbprobe.o    -o ../bin/arasanx-64 -lstdc++ -lc -lm -lrt -lpthread
> chess.h:182:6: warning: type ‘PieceType’ violates the C++ One Definition Rule [-Wodr]
> syzygy/src/tbchess.c:72:6: note: an enum with different value name is defined in another translation unit

Here are some information of the Linux machine:

> root@rock64:~/arasan-chess# lscpu
> Architecture:        aarch64
> Byte Order:          Little Endian
> CPU(s):              4
> On-line CPU(s) list: 0-3
> Thread(s) per core:  1
> Core(s) per socket:  4
> Socket(s):           1
> Vendor ID:           ARM
> Model:               4
> Model name:          Cortex-A53
> Stepping:            r0p4
> CPU max MHz:         1296.0000
> CPU min MHz:         408.0000
> BogoMIPS:            48.00
> Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
> 
> root@rock64:~/arasan-chess# lsb_release -a
> LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.4 LTS
> Release:        18.04
> Codename:       bionic
> root@rock64:~/arasan-chess# uname -a
> Linux rock64 4.4.167-1213-rockchip-ayufan-g34ae07687fce #1 SMP Tue Jun 18 20:44:49 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

So far, I have successfully compiled several other engines on this machine such as  Stockfish 230620, Lc0, Ethereal, Laser 1.8 beta, Demolito, Winter, Igel, etc. 

Would you help please? Thank you.

**Comment by rontant** [comment]
I found the executable in ~/arasan-chess/bin directory and it seems to run fine. We can just ignore the error, right?

> root@rock64:~/arasan-chess/bin# ./arasanx-64
> Arasan v22.0.0-68-g5a00e47 Copyright 1994-2020 by Jon Dart. All Rights Reserved.
> uci
> id name Arasan v22.0.0-68-g5a00e47
> id author Jon Dart
> option name Hash type spin default 32 min 4 max 64000
> option name Ponder type check default true
> option name Contempt type spin default 0 min -200 max 200
> option name Use tablebases type check default false
> option name SyzygyTbPath type string default syzygy
> option name SyzygyUse50MoveRule type check default true
> option name SyzygyProbeDepth type spin default 4 min 0 max 64
> option name MultiPV type spin default 1 min 1 max 10
> option name OwnBook type check default true
> option name Favor frequent book moves type spin default 50 min 0 max 100
> option name Favor best book moves type spin default 50 min 0 max 100
> option name Favor high-weighted book moves type spin default 50 min 0 max 100
> option name Threads type spin default 1 min 1 max 256
> option name UCI_LimitStrength type check default false
> option name UCI_Elo type spin default 2600 min 1000 max 2600
> option name Move overhead type spin default 30 min 0 max 1000
> uciok
> position fen 8/7p/6k1/1p1pKp2/1P1P4/6P1/8/8 b - - 1 48
> go movetime
> failed to open ./book.bin
> info multipv 1 depth 1 score cp -53 time 0 nodes 23 hashfull 0 pv g6g5 e5d5
> info multipv 1 depth 2 score cp -53 time 0 nodes 70 hashfull 0 pv g6g5 e5d5
> info multipv 1 depth 3 score cp -12 time 1 nodes 176 hashfull 0 pv g6g5 e5d5 g5g4
> info multipv 1 depth 4 score cp -16 time 1 nodes 324 hashfull 0 pv g6g5 e5d5 f5f4 g3f4 g5f4
> info multipv 1 depth 5 score cp -35 upperbound time 1 nodes 497 hashfull 0 pv g6g5 e5d5 f5f4 g3f4 g5f4
> info multipv 1 depth 5 score cp -42 time 3 nodes 721 hashfull 0 pv g6g5 e5d5 g5g4 d5e5 g4g3 e5f5
> info multipv 1 depth 6 score cp -42 time 4 nodes 1096 hashfull 0 pv g6g5 e5d5 g5g4 d5e5 g4g3 e5f5
> info multipv 1 depth 7 score cp -23 lowerbound time 4 nodes 1300 hashfull 0 pv g6g5 e5d5
> info multipv 1 depth 7 score cp -15 time 7 nodes 1763 hashfull 0 pv g6g5 e5d5 g5g4 d5e5 g4g3 e5f5 h7h5
> info multipv 1 depth 8 score cp -34 upperbound time 9 nodes 2361 hashfull 0 pv g6g5 e5d5 g5g4 d5e5 g4g3 e5f5 h7h5
> info multipv 1 depth 8 score cp -34 upperbound time 15 nodes 2361 hashfull 0 pv g6g5 e5d5 g5g4 d5e5 g4g3 e5f5 h7h5
> bestmove g6g5 ponder e5d5

**Comment by jdart1** [comment]
It's not an error, it's just a warning. It is related to the fact the Syzygy code uses an enum with the same name as one in the Arasan source. But that enum isn't exported or made visible to the engine. You can ignore it.
