### ISSUE TITLE
unable to compile : missing tbprobe.h

### ISSUE THREAD

**Issue by tissatussa** [jdart1/arasan-chess#30]
after a git clone i can not compile the newest Arasan (i'm using Xubuntu 20.04). First, i see some warning in the file "scoring.cpp" :

scoring.cpp: In member function ‘void Scoring::calcPawnData(const Board&, ColorType, Scoring::PawnHashEntry::PawnData&)’:
scoring.cpp:1341:55: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct Scoring::PawnHashEntry::PawnData’; use assignment or value-initialization instead [-Wclass-memaccess]

![arasan_pawndata_warning](https://user-images.githubusercontent.com/1109281/108496999-27f0d200-72ab-11eb-8151-c2ebf0b2e5f4.png)

but more important is this fatal error :

![arasan_tbprobe-h_error](https://user-images.githubusercontent.com/1109281/108497029-30490d00-72ab-11eb-8e67-a9b1b8354be5.png)

indeed, the file "syzygy/src/tbprobe.h" is missing !?

i guess "tbprobe.h" is about TableBases .. in the README you state :

The Arasan distribution does not come with any tablebase files.
Syzygy tablebases can be downloaded from https://syzygy-tables.info/

there the Download section refers to eg. http://tablebase.sesse.net but i only find folders with many seperate files, like http://tablebase.sesse.net/3-4-5/ .. what should be done with these ?  BTW. i also found http://kirill-kryukov.com/chess/tablebases-online/ which is mentioned in the text at https://github.com/syzygy1/tb but i did not look into this yet ..

i tried to change the concerning line in the file "arasan.rc" :

search.use_tablebases=false

and in the file "syzygy.cpp" i commented-out the line

#include "syzygy/src/tbprobe.h"

but i still have errors.
i guess your source code is incomplete / has a bug ..

[ to use Arasan now, i downloaded the pre-compiled Linux binary from https://arasanchess.org/downld.shtml ]

**Comment by jdart1** [comment]
Please look at https://github.com/jdart1/arasan-chess/blob/master/doc/BUILD.md. The tablebase code is included as a submodule. You need to do:
git submodule update --init --recursive
in your local repository directory.
