### ISSUE TITLE
windows gui crash

### ISSUE THREAD

**Issue by hotfics** [jdart1/arasan-chess#31]
compile successful ,but when i excute then 
arasan.cpp   at
 pDocTemplate = new CSingleDocTemplate(
        IDR_MAINFRAME,
        RUNTIME_CLASS(ArasanGuiDoc),
        RUNTIME_CLASS(ArasanMainFrame),           // main SDI frame window
        RUNTIME_CLASS(ArasanGuiView));
exception-thrown-read-access-violation
pClassThis   is   0x2B787C。

my enviroment is windows10 ,vs2019

**Comment by jdart1** [comment]
I am closing this, as not reproducible.
