### ISSUE TITLE
Scoring value from console

### ISSUE THREAD

**Issue by RichardPortelli** [jdart1/arasan-chess#32]
Hello Jon, 
Is there an equivalent of the "eval" feature in Stockfish, in Arasan?
You have a scoring method but I am not sure there is a command to get the value directly :-)
Thanks

**Comment by jdart1** [comment]
There is such a command. If you start a command window and run arasan as a console program, you can issue the "eval" command followed by a filename, and it will read a FEN position from the file and print the evaluation. It will include the score from tablebases, if available. Details of the eval are not shown, however, unless the program has been compiled with _TRACE defined in the scoring module.
