### ISSUE TITLE
Missing nnue.h file

### ISSUE THREAD

**Issue by ScallyBag** [jdart1/arasan-chess#33]
Hi John,

Arasan has been one of our main engines since the start of Picochess and the on the DGT Pi and up to the 12 Aug 2021 I’ve never had a problem compiling your engine for the Raspberry Pi.

Today I noticed your update where you’ve added NNUE, however when I try to compile it a file appears to be missing, or do I need to add something in its place?

In file included from arasanx.cpp:8:
globals.h:18:10: fatal error: nnue/nnue.h: No such file or directory
 #include "nnue/nnue.h"

Folder arasan/src/nnue is empty, where can I get file nnue.h from please?

Thanks,

Al.

**Comment by tissatussa** [comment]
i had no problem with this : the nnue.h file is in /src/nnue .. probably you did not add the option "--recursive" to the git clone line : this also downloads any submodules (if i remember correctly) ..

**Comment by jdart1** [comment]
See the [build instructions](https://github.com/jdart1/arasan-chess/blob/master/doc/BUILD.md) in the doc subdirectory. You need to do "git submodule update --init --recursive" in your local clone to obtain all dependencies.

**Comment by ScallyBag** [comment]
Thanks very much, working fine now 👍

Al.
