### ISSUE TITLE
Arasan-x64 build accidentally build with popcount?

### ISSUE THREAD

**Issue by rwbc** [jdart1/arasan-chess#36]
Version 23.3 is the first one, which doesn't run the plain x64 build here on my hardware (up to sse4.1 but no popcount).
The readme says 'modern' is just sse4.1 but with popcount, so I wonder what plain x64 is now?
My guess is that you turned on a popcount flag somwhere accidentally.

Guenther

**Comment by jdart1** [comment]
I am investigating. The plain x64 build should assume SSE2, nothing beyond that.

**Comment by jdart1** [comment]
Please try to download the engine .zip file again. I have updated with a new arasanx-64 executable. Intel's SDE tool now indicates that this has no POPCNT instructions.

**Comment by rwbc** [comment]
Thanks Jon, this one is ok now!

Would you mind to send me a compilation which has ssse3 + sse3 + sse2 for a speed comparison
with this minimal x64 build? Or may be reconsider the minimal x64 flags?
Most developers are down to ssse3/nopop for minimal requirement if at all.

Normally I would build it myself but somehow it doesn't work with Msys2 despite I have build
surely hundreds of programs and versions.
But if there would be a resonable speedup I would probably try out once a free MSVC installation,
which I always avoided so far.

Edit:
(You can see my mail address in my github profile)

**Comment by jdart1** [comment]
You should be able to build it with Cygwin.

**Comment by rwbc** [comment]
Well, the sense of msys2 is exactly that it makes cygwin obsolete on win and it also offers a bash shell in win.
So far I never had any problems with native linux developed programs building in msys2.

https://www.msys2.org/wiki/How-does-MSYS2-differ-from-Cygwin/
https://www.msys2.org/wiki/History/
