### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [jdart1/arasan-chess#37]
Can you build a Korean chess engine?

**Comment by jdart1** [comment]
I am not currently planning to have Arasan support any chess variants. Korean chess is a very different game and would not be easy to support. [H. G. Mueller](https://home.hccnet.nl/h.g.muller/chess.html) has done quite a bit of work on chess variants and has a Xiangqi engine, but not one for Korean chess, that I am aware.
