### ISSUE TITLE
Compile problems on a Raspberry Pi 32 bit

### ISSUE THREAD

**Issue by ScallyBag** [jdart1/arasan-chess#38]
Hi Jon,

I’ve never had a problem compiling Arasan before on my Raspberry Pi 4 running 32 bit Buster or Bullseye until now:

globals.cpp: In function ‘void getExecutablePath(std::string&)’:
globals.cpp:109:18: error: ‘PATH_MAX’ was not declared in this scope; did you mean ‘PATH_CHAR’?
  109 |     char result[ PATH_MAX ];
      |                  ^~~~~~~~
      |                  PATH_CHAR
globals.cpp:110:5: error: ‘result’ was not declared in this scope
  110 |     result[0] = '\0';
      |     ^~~~~~
gcc-10.1 -Wall -Wextra -fno-strict-aliasing -DUSE_INTRINSICS -DUSE_ASM -I . -DSYZYGY_TBS  -DARASAN_VERSION=v23.3.0-12-g9d61387 -std=c++17 -Ofast -flto -fno-rtti -fno-enforce-eh-specs -DNDEBUG  -DSMP -DSMP_STATS -DUSE_INTRINSICS -pthread    -c -o ../build/bitboard.o bitboard.cpp
make: *** [Makefile:309: ../build/globals.o] Error 1
make: *** Waiting for unfinished jobs....

Please advise

Thanks,

Al aka Scally on Picochess

**Comment by ScallyBag** [comment]
Hi Jon,

Please  ignore, it looks as though there is a problem with my gcc-10.1.0 compiler as gcc-8.3.0 compiles Arasan O.K.

Al.

**Comment by jdart1** [comment]
FYI, I don't support 32-bit Linux distros. It may work but it is not tested by me.
