### ISSUE TITLE
Missing gtb-probe.h

### ISSUE THREAD

**Issue by calthax** [jdart1/arasan-chess#4]
Jon Dart is it me or did you forget to add gtb-probe.h
Output of make just before it crashed
cc -Ofast -fno-rtti -fno-enforce-eh-specs -finline-functions    -Wall -fno-strict-aliasing -DUSE_INTRINSICS -DUSE_ASM  -DGAVIOTA_TBS -Imichiguel-Gaviota-Tablebases-161d6cb -DNALIMOV_TBS -I. -Itb -D_64BIT -DSMP -DSMP_STATS  -c -o ../build/gtb.o gtb.cpp
gtb.cpp:6:23: fatal error: gtb-probe.h: No such file or directory
 #include "gtb-probe.h"
                       ^
compilation terminated.
make: *** [../build/gtb.o] Error 1

**Comment by jdart1** [comment]
Tablebase support code is not part of the Arasan repository, but can be downloaded from http://arasanchess.org/downld.shtml.
