### ISSUE TITLE
Support for high DPI

### ISSUE THREAD

**Issue by dRaiNe** [jdart1/arasan-chess#42]
GUI does not scale well for high DPI displays like ´Dell U2720Q´.

Issues:
* The playing board is too small even with ´XLarge´ size set in Appearance settings.
* If user resizes the window then the board reverts to some smaller size than is ´XLarge´

System info:
* Windows 10 x64
* double screen setup with:
  * Dell U2720Q

**Comment by jdart1** [comment]
I have added an XXLarge board size in the latest release (23.5). However, I am still not sure this completely meet your requirements.
