### ISSUE TITLE
Latest release 23.5 (April 2023) detected as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by rmarquis** [jdart1/arasan-chess#47]
WHile trying to download the latest `arasan23.5.zip` (Windows engine + book only (includes 64-bit versions) from the [download](https://www.arasanchess.org/downld.shtml) page, WIndows Defender detects it as embedding the `Trojan:Win32/Wacatac.B!ml`.

This doesn't happen with the previous 23.4 release from July 2022.

**Comment by jdart1** [comment]
I am pretty sure this is a false positive. A recent Defender scan on my system shows no threats.

**Comment by rmarquis** [comment]
Hi. I can confirm Windows Defender doesn't trigger anymore. 👍
