### ISSUE TITLE
Use namespace

### ISSUE THREAD

**Issue by nguyenpham** [jdart1/arasan-chess#52]
Arasan is a very strong chess engine with a so-easy license thus it could be used in a variety of chess projects, including ones that require embedding code (say, iOS projects). However, when integrating/embedding, Arasan may have a high potential of conflicting with other code, from having the same file names, and function names to having the same library code (such as Syzygy one).
If it could use a namespace for its code, it could reduce conflict and make it much easier to embed it.

**Comment by jdart1** [comment]
I am not quite sure how to address this. Most of the code is already scoped either within a class or a namespace. Some is not: for example some the definitions in chess.h. If you need those namespace-scoped, that can be done, but I don't really want to wrap all code in a namespace. Regarding Fathom (the Syzygy code), see the README (https://github.com/jdart1/Fathom) for some suggestions on how to interface to it without creating code conflicts. You are also of course free to fork the code and implement your own scoping.

**Comment by nguyenpham** [comment]
The problem is that many chess engines and chess GUIs may have the same class names, say, "Bitboard", "Board"... That makes compilers confused when we mix their codes together.
I could do it myself but can't be as good as the author, have to do it again whenever you change the code and other people may have to face and solve the same problem.

**Comment by jdart1** [comment]
I have no near-term plans to address this. Arasan is designed to be a stand-alone executable, not a body of code that is linked with other chess code.
