### ISSUE TITLE
Arasan didn't make progress with very shallow search depths

### ISSUE THREAD

**Issue by nguyenpham** [jdart1/arasan-chess#55]
I use shallow search depths (say depth=1) as a fun/easy mode (that mode is useful for children/beginners too). I hoped Arasan could make alternative moves after repeating a while to make some (slow) progress. But it looks like accepting the draw.

[Site "iOS device"]
[Date "2023-11-27"]
[Round "1"]
[White "White"]
[Black "Arasan"]
[Result "*"]
[TimeControl "depth 1"]
[Time "08:58:15"]

1. e4 e6 2. Nf3 Nc6 3. d4 Nf6 4. e5 Nd5
5. c4 Nb4 6. Bd2 a5 7. a3 Na6 8. b4 axb4
9. axb4 Bxb4 10. Bxb4 Nxb4 11. Nc3 d6 12. exd6 cxd6
13. d5 O-O 14. dxe6 Bxe6 15. Be2 Re8 16. O-O Bf5
17. Nd4 Bg6 18. Re1 Nc5 19. Bf3 Qg5 20. Rxa8 Rxa8
21. g3 Nd3 22. Re4 Bxe4 23. Bxe4 Ne5 24. f4 Qg4
25. fxe5 Qxd1+ 26. Nxd1 Nxe4 27. exd6 Nxd6 28. c5 Ra1
29. h4 Rxd1+ 30. Kg2 Rxd4 31. cxd6 Rxd6 32. g4 Rd4
33. Kg3 b5 34. g5 b4 35. Kf3 Rxh4 36. Ke3 b3
37. Kd2 Rb4 38. Kc1 h5 39. Kb2 h4 40. Kc3 b2
41. Kxb4 b1=Q+ 42. Kc4 h3 43. Kc3 h2 44. Kd4 h1=Q
45. Ke5 Kh7 46. Kf4 Kg6 47. Kg4 Kh7 48. Kf4 Kg6
49. Kg4 Kh7 50. Kf4 g6 51. Kg4 Kg7 52. Kf4 Kh7
53. Kg4 Kg7 54. Kf4 Kg8 55. Kg4 Kh7 56. Kf4 Kg7
57. Kg4 Kh7 58. Kf4 Kg7 59. Kg4 Kg8 60. Kf4 Kf8
61. Kg4 Ke7 62. Kf4 Ke6 63. Kg4 Ke5 64. Kg3 Kf5
65. Kf2 Kxg5 66. Ke3 Kg4 67. Kf2 g5 68. Ke3 f5
69. Kd4 f4 70. Ke5 f3 71. Kf6 f2 72. Ke6 f1=Q
73. Ke7 Kf3 74. Ke6 Kg3 75. Ke5 Kf3 76. Kd4 Kf2
77. Ke5 Kf3 78. Kd4 Kf2 79. Ke5 Kg3 80. Kd4 Kg2
81. Ke5 Kg3 82. Kd4 Kg2 83. Ke5 Kh3 84. Kd4 Kh2
85. Ke5 Kh3 86. Kd4 Kh2 87. Ke5 g4 88. Kd4 Kg1
89. Ke5 Kf2 90. Kd4 Kg1 91. Ke5 Kf2 92. Kd4 Ke2
93. Ke5 Ke3 94. Kd6 Kd2 95. Ke5 Ke3 96. Kd6 Kd2
97. Ke5 g3 98. Kd4 Ke1 99. Ke3 g2 100. Kd4 Kd1
101. Ke3 Ke1 102. Kd4 Kd1 103. Ke5 Kc1 104. Kd4 Kb2
105. Kc5 Ka1 106. Kd4 Ka2 107. Kd5 Ka1 108. Kd4 Ka2
109. Kd5 Ka1 110. Kd4 Kb2 111. Kd5 Kc1 112. Kd4 Kc2
113. Kd5 Kc1 114. Kd4 Kc2 115. Kd5 Kd1 116. Kd4 Kc1
117. Kd5 Kd1 118. Kd4 Kc1 119. Kd5 Kb2 120. Kd4 Ka1
121. Ke5 Ka2 122. Kd4 Ka1 123. Kd5 Ka2 124. Kd4 Ka3
125. Kd5 Ka2 126. Kd4 Ka3 127. Kd5 Kb2 128. Kd4 Kb3
129. Kd5 Kc2 130. Kd4 Kd2 131. Kd5 Ke1 132. Kd4 Kd2
133. Kd5 Ke1 134. Kd4 Ke2 135. Kd5 Kd2 136. Kd4 Ke1
137. Kd5 Kd2 138. Kd4 Ke1 139. Kd5 Ke2 140. Kd4 Kf2
141. Kd5 Kg1 142. Kd4 Kf2 143. Kd5 Kg1 144. Kd4 Kh2
145. Kd5 Kg3 146. Kd4 Kh2 147. Kd5 Kg3 148. Kd4 Kf3
149. Kd5 g1=Q 150. Kd6 Ke2 151. Kd7 Kd1 152. Kd6 Kc1
153. Kd7 Kd1 154. Kd6 Kc1 155. Kd7 Kd1 156. Kd6 Kc1
157. Kd7 Kd1 158. Kd6 Kc1 159. Kd7 Kd1 160. Kd6 Kc1
161. Kd7 Kd1 162. Kd6 Kc1 163. Kd7 Kd1 164. Kd6 Kc1
165. Kd7 Kd1 166. Kd6 Kc1 167. Kd7 Kd1 168. Kd6 Kc1
169. Kd7 Kd1 170. Kd6 Kc1 171. Kd7 Kd1 172. Kd6 Kc1

**Comment by jdart1** [comment]
Arasan has a strength reduction feature, so I'd recommend that you use that, if you want to have an easier opponent. Regarding not making progress, you can't expect much in the way of strategy when at depth 1. Regading draws, generally it will try to avoid draws against weaker opponents and be more likely to accept them against a higher-rated opponent. If playing on a chess server, it will use the server ratings to control this. You can manually set the Contempt option to control this (but not in the native Arasan GUI - it doesn't support that at present).
