### ISSUE TITLE
24.2 loses on time for me - debug files attached.

### ISSUE THREAD

**Issue by GrahamCCRL** [jdart1/arasan-chess#57]
[Dbg00005_PlentyChess10064-bit_Arasan24264-bit.txt](https://github.com/jdart1/arasan-chess/files/14914008/Dbg00005_PlentyChess10064-bit_Arasan24264-bit.txt)
[Dbg00006_Arasan24264-bit_PlentyChess10064-bit.txt](https://github.com/jdart1/arasan-chess/files/14914016/Dbg00006_Arasan24264-bit_PlentyChess10064-bit.txt)

**Comment by GrahamCCRL** [comment]
Okay. Will do.

**Comment by jdart1** [comment]
Also, what chess interface was in use?

**Comment by GrahamCCRL** [comment]
ChessGUI - as I 've always used.

**Comment by GrahamCCRL** [comment]
Hi Jon,

a CEGT tester has confirmed that Arasan has time losses in the Arena
interfcae as well.

Graham.

**Comment by GrahamCCRL** [comment]
I'm using Arasan as a uci engine with the rc file.

**Comment by GrahamCCRL** [comment]
*108TH AMATEUR SERIES (Division 1)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion and the bottom engine will
face automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Stockfish 16.1 64-bit
Berserk 13 64-bit
RubiChess 20241112 64-bit
Caissa 1.18 64-bit
Obsidian 11.0 64-bit
Alexandria 6.1.0 64-bit
PlentyChess 1.0.0 64-bit *(promoted)*
Seer 2.8.0 64-bit
Rebel 16.3 64-bit
Clover 6.1 64-bit
CS Tal 2.0 64-bit
Rofchade 3.1 64-bit
Igel 3.5.0 64-bit
Arasan 24.2 64-bit *(promoted)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by jdart1** [comment]
I have reproduced this with Arena. Still working on root-causing it.

**Comment by GrahamCCRL** [comment]
Thanks Jon.
I'll replace 24.1 with 24.2 in my Amateur Division 1 once it's ready.

Graham.

**Comment by GrahamCCRL** [comment]
Is there a new exe coming soon?

**Comment by jdart1** [comment]
Yes, may take 1-2 days

**Comment by GrahamCCRL** [comment]
No problem.
I'll run the Araan games in a bunch for Division 1 once it's done. :-)
