### ISSUE TITLE
bug on "fivefold repetition"

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jdart1/arasan-chess#6]
Hi,
when arasan is a "fivefold repetition" situation, it returns a null move in standard searching.
This crushes picochess, see here: https://github.com/jromang/picochess/issues/230

On infinite mode it works.
Below is the log with typing in the uci-commands by hand.

Arasan v20.0.0-26-g15e1f6b Copyright 1994-2017 by Jon Dart. All Rights Reserved.

uci
id name Arasan v20.0.0-26-g15e1f6b
id author Jon Dart
option name Hash type spin default 32 min 4 max 64000
option name Ponder type check default true
option name Use tablebases type check default false
option name Tablebases type combo var None var Syzygy default None
option name SyzygyTbPath type string default syzygy
option name SyzygyUse50MoveRule type check default true
option name SyzygyProbeDepth type spin default 4 min 0 max 64
option name MultiPV type spin default 1 min 1 max 10
option name OwnBook type check default true
option name Book selectivity type spin default 50 min 0 max 100
option name Threads type spin default 1 min 1 max 64
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 2600 min 1000 max 2600
uciok
position fen 6k1/4R3/6K1/8/8/8/8/8 w - - 0 1 moves e7f7 g8h8 f7e7 h8g8 e7f7 g8h8 f7e7 h8g8 e7f7
go wtime 100 btime 100
info multipv 1 depth 0 score cp 0 time 0 nodes 0 hashfull 0
bestmove 0000

go infinite
info multipv 1 depth 1 score cp 0 time 0 nodes 2 hashfull 0 pv g8h8
info multipv 1 depth 2 score cp 0 time 0 nodes 4 hashfull 0 pv g8h8

**Comment by jdart1** [comment]
Arasan does not support the fivefold repetition rule adopted by FIDE. Nor do most engines or chess interfaces. After a threefold repetition it will consider the game a draw. So returning a null move is actually a reasonable behavior IMO given that most UIs will adjudicate it to a draw. The bug report you linked to though mentions an illegal move -- if there is a way to make Arasan make an illegal move that is a bug that should be fixed.

**Comment by LocutusOfPenguin** [comment]
Thanks for yr comment.
But as i said, the other engines send back a Kh8 move (important!) like yr engine also doing during infinite mode. Therefore your engine behaves different to the others.

If y think a null move is the correct answer to this situation the infinite search should also do so.

For me the prefered answer should be Kh8 which all engines i know also doing. Forgive me, but that would make me write extra code (prob. also includes python-chess) for arasan only to handle null moves in PVs.

**Comment by jdart1** [comment]
I will look into it further.

**Comment by jdart1** [comment]
Should be fixed now, in commit e685d3a.

**Comment by MichaelB7** [comment]
Just FYI,The "five-fold repetition rule" (Article 9.6) is totally different from the "three fold repetition rule" (Article 9.2) and written for the arbitrator in mind, not the players.  Article 9.6 "
If one or both of the following occur(s) then the game is drawn:
the same position has appeared, as in 9.2b, for at least five consecutive alternate moves by each player.
any consecutive series of 75 moves have been completed by each player without the movement of any pawn and without any capture. If the last move resulted in checkmate, that shall take precedence."

Article 9.2 "The game is drawn, upon a correct claim by a player having the move, when the same position for at least the third time (not necessarily by a repetition of moves):
is about to appear, if he first writes his move, which cannot be changed, on his scoresheet and declares to the arbiter his intention to make this move, or
has just appeared, and the player claiming the draw has the move.
Positions areconsidered the same if and only if the same player has the move, pieces of the same kind and colour occupy the same squares and the possible moves of all the pieces of both players are the same. Thus positions are not the same if:
at the start of the sequence a pawn could have been captured en passant.
a king or rook had castling rights, but forfeited these after moving. The castling rights are lost only after the king or rook is moved."

The language is not remotely similar.  Article 9.2 was for the player to claim a draw, Article 9.6 was for the Arbitrator to declare a draw.  Totally irrevelant for computer chess.
