### ISSUE TITLE
NNUE not used when running bench for profile build with NMake

### ISSUE THREAD

**Issue by lordlouckster** [jdart1/arasan-chess#60]
1. Can this even be fixed, given that NMake can't run UCI commands _inside_ Arasan?
2. Does it even matter for building the fastest binaries?

**Comment by jdart1** [comment]
You can fix this by copying the network file and arasan.rc (from the src directory) into the profile subdirectory, where execution of the program for profiling takes place. Adjust the TB path in arasan.rc if needed: this will also allow profiling the Syzygy code. But it probably doesn't make a huge difference: the benefit from profiling is relatively small.

**Comment by jdart1** [comment]
Closing since there is a workaround.
