### ISSUE TITLE
Tuner software

### ISSUE THREAD

**Issue by GiovanniLavorgna** [jdart1/arasan-chess#61]
Hi John. I was trying the tuner software on a labelled epd file, but it get's stacked for ever. Other epd files ran instead smoothly. I enclose the culprit epd file. However, I had to use the '.txt' extension, because the system wasn't letting me to upload it. Thanks in advance.

./tuner test_labelled.ped
warning: no NNUE file path was set, network not loaded
warning: opening book not found or invalid
parameter count: 735 (717 tunable)
iteration 1

[test_labelled.txt](https://github.com/user-attachments/files/17540473/test_labelled.txt)

**Comment by jdart1** [comment]
I'm not going to fix this. The tuner is removed in the current master branch.
