### ISSUE TITLE
arasan v20.1.0 crushing on ubuntu (16.04) 64bit

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jdart1/arasan-chess#7]
Hi,

git checkout v20.1.0 > compile > run > results in a "memory dump error"
same for "master"

with checkout v20.0.0 it works.

**Comment by jdart1** [comment]
I need some more info. I have been running v20.1.0 and recent snapshots on Ubuntu routinely. A few questions:
1. Do the binaries at http://arasanchess.org/downld.shtml work for you? These were built from the v20.1.0 tag.
2. If you are experiencing a crash, please try compiling with the DEBUG line uncommented in the makefile and run under gdb. Then you can get a stack trace where the crash occurs.
3. You can expect "master" to be somewhat unstable but if is crashing please specify the commit number you tried, and as above, if possible submit a stack trace.

**Comment by LocutusOfPenguin** [comment]
hmmm...cant recreate my problem (Compile & Run works now).
Its perhaps from old *.o files laying around? Well, sorry for disturb! => close.
