### ISSUE TITLE
Problems with compile  (now)

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jdart1/arasan-chess#8]
Hi,

first i tried:
git submodule update --init --recursive
(perhaps you should mention something like this, somewhere)

But i still get:
cc -x c++ -std=c++11 -Wall -fno-strict-aliasing -DUSE_INTRINSICS -DUSE_ASM -I. -DSYZYGY_TBS -DARASAN_VERSION=v20.2.0-30-g07ed0a6 -D_64BIT -Ofast -fno-rtti -fno-enforce-eh-specs -msse3 -DNDEBUG  -c syzygy/src/tbprobe.c -o ../build/tbprobe.o
In file included from syzygy/src/tbprobe.c:29:0:
syzygy/src/tbprobe.h:27:22: fatal error: tbconfig.h: Datei oder Verzeichnis nicht gefunden

means:  file not found

Can y help?
Jürgen

**Comment by jdart1** [comment]
Please pick up commit 01a3440 - should fix your issue.
