### ISSUE TITLE
is "searchmoves" supported?

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jdart1/arasan-chess#9]
Hi,
for "alternative moves" i need the "go searchmoves" function. It seems to me, that arasan doesnt support it cause when i try it on SF (and many other engines) it works but with Arasan i get the same move again and again.

If not supported, can y say something when it can be expected?

Jürgen

**Comment by jdart1** [comment]
No, it is not currently supported. Will look into it soon.

**Comment by jdart1** [comment]
Fixed in commit 8f1caeb
